
import "./globals.css";


export const metadata = {
  title: "Welcome to Skramby",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h3>I am Navbar</h3>
        {children}
        <h3>I am Footer</h3>
      </body>
    </html>
  );
}
